---
situation_assessment:
    ring_buffer_length: 10
    use_orientation: false
    tf_bridge:
        track_robot: true
        track_agents: true
        track_objects: true
        track_groups: true
    human_names:
        - HERAKLES_HUMAN1
        # - HERAKLES_HUMAN2
    object_names:
        - bottle 
    simulation: true
    robot_name: PR2_ROBOT

    action_monitoring:
        use_database: false
        trigger_distance: 0.5
        actions_to_monitor:
          - pick    
        actions_details:
            pick:
                target: main_object
                monitor_part: hand
        affordances:
            bottle:
                - pick
