---
situation_assessment:
    #doc_path: /home/mfiore/ros_workspaces/my_spencer_ws/src/spencer_situation_assessment/spencer_symbolic_map/maps/Adream_demo/
    #doc_name: Adream_demo
    #doc_path: /home/mfiore/ros_workspaces/my_spencer_ws/src/supervision/spencer_integration/ALUFR/
    #doc_name: ALU_FR_building_101
    doc_path: /home/mfiore/ros_workspaces/my_spencer_ws/src/spencer_situation_assessment/spencer_symbolic_map/maps/LAAS_new/
    doc_name: LAAS_new
    information_screen_area_b: 2
    information_screen_area_h: 3
    gate_area_b: 3
    gate_area_h: 5
    ring_buffer_length: 10
    use_orientation: false
    tf_bridge:
        track_robot: true
        track_agents: true
        track_objects: false
        track_groups: true
    spencer_bridge:
        track_robot: false
        track_agents: false
        track_objects: true
        track_groups: false
    human_names:
        - HERAKLES_HUMAN1 
        - HERAKLES_HUMAN2
        #object_names: 