---
situation_assessment:
    doc_path: /home/mfiore/ros_workspaces/my_spencer_ws/src/spencer_situation_assessment/spencer_symbolic_map/maps/
    doc_name: spencer_map
    triangle_b: 2
    triangle_h: 3
    ring_buffer_length: 10
    use_orientation: false
    tf_bridge:
        track_robot: true
        track_agents: true
        track_objects: false
        track_groups: true
    spencer_bridge:
        track_robot: false
        track_agents: false
        track_objects: true
        track_groups: false
    human_names:
        - HERAKLES_HUMAN1 
        - HERAKLES_HUMAN2
        #object_names: 