---
situation_assessment:
    starting_world_state_file: /home/mfiore/ros_workspaces/indigo_ws/src/scenarios/demo_observer/world_state.xml
    ring_buffer_length: 10
    use_orientation: false
    tf_bridge:
        track_robot: true
        track_agents: true
        track_objects: true
        track_groups: true
    human_names:
        - human1
        # - HERAKLES_HUMAN2
    object_names:
        - waterbottle
        - teabottle
        - mug
        - table
        - shelf1
        - shelf2
        - shelf3
        - sidetable
        - sofa
    locations:
        - livingroom
        - outside
        - table
        - shelf1
        - shelf2
        - shelf3
        - this
    locations_depth:
        livingroom: 1
        outside: 1
        bathroom: 1
        table: 2
        shelf1: 2
        shelf2: 2
        shelf3: 2
        this: 0
    simulation: true
    robot_name: PR2_ROBOT

